import React, { useState } from "react";

import "../../styles/securitystyles.css";
const TwoFactorAuth = () => {
  return (
    <div>
      <h3 style={{ color: "#9dcd5a", fontWeight: "bold" }}>
        Two-factor Authentication
      </h3>
      <div className="security-settings__wrapper">
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <p className="security-settings-textheading__text">
            Two-factor authentication is a feature that adds an extra layer of
            protection to your account. When you enable 2FA, you will need to
            enter your password and then a code sent to your mobile device or
            generated by an authenticator app.
          </p>
          <button className="security-settings-enable__btn">Enable</button>
        </div>

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginTop: "20px",
          }}
        >
          <div>
            <p className="security-settings-emailrecovery__text">
              Email Recovery
            </p>
            <p className="security-settings-emaildetail__text">
              emailrecover@gmail.com
            </p>
          </div>
          <button className="security-settings-setup__btn">Setup</button>
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginTop: "20px",
          }}
        >
          <div>
            <p className="security-settings-smsrecovery__text">SMS Recovery</p>
            <p className="security-settings-smsnumber__text">021-0299-7765</p>
          </div>
          <button className="security-settings-setup__btn">Setup</button>
        </div>
      </div>
    </div>
  );
};

const PasswordChange = () => {
  const [activeChangePassword, setActiveChangePassword] = useState(false);
  return (
    <div>
      <h3 style={{ color: "#9dcd5a", fontWeight: "bold" }}>Password</h3>
      <div className="security-settings__wrapper">
        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <div>
            <p className="security-password__text">Change Password</p>
            <p className="security-password-textheading__text">
              Changing your password regularly is an important way to keep your
              account secure. When you update your password, make sure it’s
              strong by using a mix of letters, numbers, and special characters.
              Avoid using easily guessable information like common words or your
              name.
            </p>
            {activeChangePassword === false ? (
              <button
                className="security-password-change__btn"
                onClick={() => setActiveChangePassword(true)}
              >
                Update
              </button>
            ) : (
              <div>
                <br />
                <p className="security-password-input__text">
                  Current Password
                </p>
                <input type="password" className="security-password-input" />
                <p className="security-password-input__text">New Password</p>
                <input type="password" className="security-password-input" />
                <p className="security-password-input__text">
                  Confirm Password
                </p>
                <input type="password" className="security-password-input" />
                <br />
                <button
                  className="security-password-cancelchange__btn"
                  onClick={() => setActiveChangePassword(false)}
                >
                  Cancel
                </button>
                <button className="security-password-change__btn">
                  Submit
                </button>
              </div>
            )}
          </div>
          <div className="security-password-rules__wrapper">
            <p className="security-password__text">Rules for Password</p>
            <p className="security-password-rules__text">
              To create a new password, you have to meet all of the following
              requirements:
            </p>
            <ul className="security-password-rules-lists">
              <li>Minimum of 8 characters</li>
              <li>At least one number</li>
              <li>At least one special character</li>
              <li>Can not be the same as the previous</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
const Security = () => {
  return (
    <div>
      <TwoFactorAuth />
      <br />
      <br />
      <PasswordChange />
    </div>
  );
};

export default Security;
